server:
  port: 8080
spring:
  application:
    name: simple-boot-mock-server
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/ORCLCDB.localdomain
    username: MOONTEA
    password: MOONTEA1234
    hikari: # 连接池配置
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create
    show-sql: true