--------------------------------------------------------
--  DDL for Table MOCK_DATA
--------------------------------------------------------

  CREATE TABLE "MOONTEA"."MOCK_DATA" 
   (	"ID" NUMBER(19,0), 
	"CONTENT" VARCHAR2(255 CHAR), 
	"CONTENT_TYPE" VARCHAR2(255 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"DEFAULT_FLAG" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"HEADERS" VARCHAR2(255 CHAR), 
	"MOCK_PARAMS" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_DATE" TIMESTAMP (6), 
	"RESPONSE_BODY" VARCHAR2(255 CHAR), 
	"STATUS" NUMBER(10,0), 
	"STATUS_CODE" NUMBER(10,0), 
	"TITLE" VARCHAR2(255 CHAR), 
	"MOCK_GROUP_ID" NUMBER(19,0), 
	"MOCK_REQUEST_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011645
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOONTEA"."SYS_C0011645" ON "MOONTEA"."MOCK_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MOCK_DATA
--------------------------------------------------------

  ALTER TABLE "MOONTEA"."MOCK_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MOONTEA"."MOCK_DATA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOCK_DATA
--------------------------------------------------------

  ALTER TABLE "MOONTEA"."MOCK_DATA" ADD CONSTRAINT "FKAE971L91GTLEN2IGLLVIHYGGO" FOREIGN KEY ("MOCK_GROUP_ID")
	  REFERENCES "MOONTEA"."MOCK_GROUP" ("ID") ENABLE;
  ALTER TABLE "MOONTEA"."MOCK_DATA" ADD CONSTRAINT "FKEVY3JPLD497OXCX0TJS24HUOG" FOREIGN KEY ("MOCK_REQUEST_ID")
	  REFERENCES "MOONTEA"."MOCK_REQUEST" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Table MOCK_GROUP
--------------------------------------------------------

  CREATE TABLE "MOONTEA"."MOCK_GROUP" 
   (	"ID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"GROUP_NAME" VARCHAR2(255 CHAR), 
	"GROUP_PATH" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011647
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOONTEA"."SYS_C0011647" ON "MOONTEA"."MOCK_GROUP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MOCK_GROUP
--------------------------------------------------------

  ALTER TABLE "MOONTEA"."MOCK_GROUP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MOONTEA"."MOCK_GROUP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table MOCK_REQUEST
--------------------------------------------------------

  CREATE TABLE "MOONTEA"."MOCK_REQUEST" 
   (	"ID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"METHOD" VARCHAR2(255 CHAR), 
	"MOCK_PARAMS" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_DATE" TIMESTAMP (6), 
	"REQUEST_PATH" VARCHAR2(255 CHAR), 
	"STATUS" NUMBER(10,0), 
	"MOCK_GROUP_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011649
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOONTEA"."SYS_C0011649" ON "MOONTEA"."MOCK_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MOCK_REQUEST
--------------------------------------------------------

  ALTER TABLE "MOONTEA"."MOCK_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MOONTEA"."MOCK_REQUEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOCK_REQUEST
--------------------------------------------------------

  ALTER TABLE "MOONTEA"."MOCK_REQUEST" ADD CONSTRAINT "FKMJSXTWD5WKCLMV53CBDDS6XNI" FOREIGN KEY ("MOCK_GROUP_ID")
	  REFERENCES "MOONTEA"."MOCK_GROUP" ("ID") ENABLE;
